# [실습1단계: 하] 순차 탐색의 한계

```python
#기본 논리값 배열 생성 및 np.nditer를 활용한 단순 반복문
#np.nditer
import numpy as np
#1. 배열 생성 및 조건 확인
arr = np.array([3,7,2,8,5,10])
condition = arr > 5 # [False, True, False, True, False, True]

#2. 단순 for문 탐색(느린 방식)
result = []
for x in np.nditer(arr):
    if x > 5:
        result.append(x)
print(result) #결과: [7,8,10]
```

[numpy.nditer함수 매뉴얼](https://numpy.org/devdocs/reference/generated/numpy.nditer.html)

In [3]:
#기본 논리값 배열 생성 및 np.nditer를 활용한 단순 반복문
#np.nditer
import numpy as np
#1. 배열 생성 및 조건 확인
arr = np.array([3,7,2,8,5,10])
condition = arr > 5 # [False, True, False, True, False, True]

#2. 단순 for문 탐색(느린 방식)
result = []
for x in np.nditer(arr):
    print(x)
    if x > 5:
        result.append(x)
print(result) #결과: [7,8,10]

3
7
2
8
5
10
[array(7), array(8), array(10)]


# [실습2단계: 중] 마스킹과 np.apply_along_axis

---  

```python
import numpy as np

# -------------------------------
# 1. 다중 조건을 활용한 불리언 마스킹
# -------------------------------

# 예제 배열 생성
arr = np.array([5, 12, 25, 48, 51, 7, 33, 60])

# 조건:
# 10보다 크고 AND 50보다 작은 값만 선택
mask = (arr > 10) & (arr < 50)

# 조건에 맞는 데이터 추출
filtered_data = arr[mask]

print("원본 배열:")
print(arr)

print("\n불리언 마스크:")
print(mask)

print("\n조건에 맞는 데이터:")
print(filtered_data)
```

---  

```python
import numpy as np

# -------------------------------
# 2. np.apply_along_axis 적용
# -------------------------------

# 각 행(row)의 최대값 - 최소값 계산 함수
def custom_logic(row):
    return np.max(row) - np.min(row)

# 5x5 랜덤 행렬 생성
matrix = np.random.randint(0, 100, size=(5, 5))

# 각 행(axis=1)에 함수 적용
range_results = np.apply_along_axis(custom_logic, 1, matrix)

print("\n랜덤 행렬:")
print(matrix)

print("\n각 행의 범위(최대값 - 최소값):")
print(range_results)
```

---  


In [9]:
import numpy as np
# 1. 다중 조건을 활용한 불리언 마스킹
# 예제 배열 생성
arr = np.array([5, 12, 25, 48, 51, 7, 33, 60])
# 조건:
# 10보다 크고 AND 50보다 작은 값만 선택
mask = (arr > 10) & (arr < 50)
# 조건에 맞는 데이터 추출
filtered_data = arr[mask]

print("원본 배열:")
print(arr)
print("\n불리언 마스크:")
print(mask)
print("\n조건에 맞는 데이터:")
print(filtered_data)



원본 배열:
[ 5 12 25 48 51  7 33 60]

불리언 마스크:
[False  True  True  True False False  True False]

조건에 맞는 데이터:
[12 25 48 33]


In [8]:
import numpy as np
# 2. np.apply_along_axis 적용
# 각 행(row)의 최대값 - 최소값 계산 함수
def custom_logic(row):
    return np.max(row) - np.min(row)

# 5x5 랜덤 행렬 생성
matrix = np.random.randint(0, 100, size=(5, 5))

# 각 행(axis=1)에 함수 적용
range_results = np.apply_along_axis(custom_logic, 1, matrix)

print("\n랜덤 행렬:")
print(matrix)
print("\n각 행의 범위(최대값 - 최소값):")
print(range_results)





랜덤 행렬:
[[19 76 93 86 46]
 [97 95 89 33 37]
 [70 82 55 27 68]
 [84 30 66  6 80]
 [ 9 15  7 21 53]]

각 행의 범위(최대값 - 최소값):
[74 64 55 78 46]


# [실습 3단계: 상] 1000배 느린 코드(The Loop Approach)
* 초보자가 작성한 순환문 기반의 배터리 상태 판별

```python

import numpy as np

#1,000만 대의 드론 배터리 데이터
battery_levels  = np.random.randint(0,101,size=10000000)

status_list = []
#치명적인 병목 지점 (Bottleneck)
for level in battery_levels:
    if level >= 70:
        status_list.append('Green')
    elif level >= 40:
        status_list.append('Yellow')
    else:
        status_list.append('Red')
```
        

In [12]:
import numpy as np
import time

#1,000만 대의 드론 배터리 데이터
battery_levels  = np.random.randint(0,101,size=10000000)

#배터리 데이터 상태 측정
start  = time.time()

status_list = []
#치명적인 병목 지점 (Bottleneck)
for level in battery_levels:
    if level >= 70:
        status_list.append('Green')
    elif level >= 40:
        status_list.append('Yellow')
    else:
        status_list.append('Red')

end = time.time()
print("실행시간: ", end - start, "초")

실행시간:  1.5885043144226074 초


# [실습 3단계: 상] np.select를 활용한 완벽한 벡터화
* 반복문을 완전히 제거한 텔레포트(Teleportation) 기법

```python

import numpy as np

#1,000만 대의 드론 배터리 데이터
battery_levels  = np.random.randint(0,101,size=10000000)

#조건(Conditions)과 결과(Choices)를 배열로 정의
Conditions = [
    (battery_levels >= 70), 
    (battery_levels >= 40) & (battery_levels < 70),
    (battery_levels < 40)
]
Choices = ['Green', 'Yellow', 'Red']

#단 한 줄로 1,000만 개 데이터 동시 처리 (벡터화)
status_array = np.select(Conditions, Choices)

```
        

In [14]:
# np.select를 활용한 완벽한 벡터화
# 반복문을 완전히 제거한 텔레포트(Teleportation) 기법

import numpy as np
import time

#1,000만 대의 드론 배터리 데이터
battery_levels  = np.random.randint(0,101,size=10000000)

#배터리 데이터 상태 측정
start = time.time()

#조건(Conditions)과 결과(Choices)를 배열로 정의
Conditions = [
    (battery_levels >= 70), 
    (battery_levels >= 40) & (battery_levels < 70),
    (battery_levels < 40)
]
Choices = ['Green', 'Yellow', 'Red']

#단 한 줄로 1,000만 개 데이터 동시 처리 (벡터화)
status_array = np.select(Conditions, Choices)

end = time.time()
print("실행시간: ", end - start, "초")

실행시간:  0.22976016998291016 초
